title: ro2share
author: ro2share
email: alexgarciac@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ro2share
github_username:  alexgarciac

header_pages:
  - usecases.md
  - settingitup.md
  - gettingthecode.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
